### ISSUE TITLE
Can' interact with world. Chunks won't load.

### ISSUE THREAD

**Issue by DarkoGNU** [themoonisacheese/2bored2wait#4] opened 2019-03-12 14:54 UTC
Today I joined. I instantly walked through a nether portal to the overworld. I killed a few zombies and I walked a few hundred blocks away. I was only able to destroy one sand block then. I couldn't attack anything, I couldn't place any block and I couldn't destroy any block - broken blocks reappeared, placed blocks disappeared. New chunks didn't load, although loaded chunks seemed to be working (partially) correctly - new mobs spawned, but they didn't follow me. This issue may be related to using a hacked client - Impact.

**Comment by DarkoGNU** [comment] 2019-03-12 15:18
I can add that it happened directly after trying to ride a horse. It doesn't look like a coincidence. Impact's Riding feature was turned on, although the horse had a saddle.

**Comment by themoonisacheese** [comment] 2019-03-12 16:03
I'm assuming you disconnected before trying to get off the horse. Could you please try again, getting off the horse and breaking blocks then? If it works then it's the same problem as #2 and the undelying problem is that the rided entity's position never updates

**Comment by DarkoGNU** [comment] 2019-03-14 17:17
Confirmed - after clicking shift everything goes back to normal. It persists even after disconnecting - clicking shift (or something killing the rideable entity, I guess) is necessary.

**Comment by themoonisacheese** [comment] 2019-03-25 21:02
closed as duplicate of #2

**Closed by themoonisacheese** 2019-03-25 21:02 UTC
Labels: bug, critical
