### ISSUE TITLE
Too much time difference between 2B2W ETA and Real 2B2T ETA

### ISSUE THREAD

**Issue by onayB09** [themoonisacheese/2bored2wait#241] opened 2021-04-01 06:23 UTC
Hello. When I Started The Queue command promt Saying 2 Hours Left But When I Look At 2B2T queue its saying 9 hours. thanks if someone helps me.
![image](https://user-images.githubusercontent.com/53120690/113251908-c1a89780-92cb-11eb-93b3-c630ae0524ae.png)
![image](https://user-images.githubusercontent.com/53120690/113252002-e8ff6480-92cb-11eb-802a-f18860e0da53.png)

**Comment by MrGeorgen** [comment] 2021-04-01 08:24
yeah thats a big difference. I'll close this because it is a duplicate of #141.
It's relativly esay to calculate a more acurred time after you waited for
maybe half an hour already. I'll do that the next days.
However calculating a good time right away is difficult.

**Closed by MrGeorgen** 2021-04-01 08:24 UTC
