### ISSUE TITLE
faulty binary releases

### ISSUE THREAD

**Issue by nickcat325** [themoonisacheese/2bored2wait#315] opened 2021-05-19 02:43 UTC
When running the Linux 64bit program the words "Segmentation fault" come up. 0.1.29 still works.

**Comment by czho** [comment] 2021-05-19 03:06
is this on the exec or in the straight node js

**Comment by themoonisacheese** [comment] 2021-05-19 09:11
> 
> 
> A new version was released, can you please try again? Maybe it was a one-off problem with the last release.

0.1.31 does not change anything code-related. maybe the compile artifacts were wrong for some reason but if it's an actual code problem then this version fixes nothing.

**Comment by rob9315** [comment] 2021-05-19 12:26
@themoonisacheese A javascript code problem shouldn't cause a Segmentation fault, I think it was just a compile artifact

**Comment by nickcat325** [comment] 2021-05-19 19:06
The update fixed the problem. Thank you.

**Comment by MrGeorgen** [comment] 2021-05-20 07:06
the problem is this happened also multiple times before. If you look at the
releases there are often binaries around 25 MB. While I did not test all of
these, they can not be working because node is already around double the size.
I do not know where this comes from, I never had this issue on my machine

**Comment by nickcat325** [comment] 2021-05-21 20:48
There are some issues with 0.1.34.  When running the Linux version of the program it says, "New Update Available! → 0.1.34".  The other issue is if local.json file does not have the text "discordBot": false it crashes/errors out. "discordBot": true does the same thing but that may be because I do not have a discord token.
If discordBot does not exist in the config, it needs to ask, Do you have a Discord bot? [N] :

**Comment by KozmikNano** [comment] 2021-05-21 20:50
Try deleting your local.js and see if that fixes any thing. Also it is writes that message is showing up about that update. Let me have a look at that.

**Comment by nickcat325** [comment] 2021-05-21 21:05
@KozmikNano I deleted the config and it works but a config update would be an improvement.

**Comment by rob9315** [comment] 2021-05-21 23:03
I did not consider that discordBot could be undefined /not set when releasing v 0.1.34. It will be fixed immediately

**Comment by rob9315** [comment] 2021-05-22 00:53
The releases indeed do not compile correctly nearly each time. This time alphine was hit

**Comment by themoonisacheese** [comment] 2021-05-22 11:29
after a quick look at the logs there doesn't seem  to be anything going wierd during the build, so i'm not really sure where to go from here. 

Maybe switching from nexe v4 beta to nexe v3 stable would fix this?

**Comment by MrGeorgen** [comment] 2021-06-03 09:25
> after a quick look at the logs there doesn't seem to be anything going wierd during the build, so i'm not really sure where to go from here.
> 
> Maybe switching from nexe v4 beta to nexe v3 stable would fix this?

I don't think it is a nexe problem, more somthing specific to the action
(uploading?), because I rebuild it like 20 time or so on my machine and it always worked

**Comment by nickcat325** [comment] 2021-06-05 02:46
The update is faulty, 2bored2wait-linux-x64-0.1.40, but 0.1.39 still works. The output of 0.1.40 is Segmentation fault.

**Comment by themoonisacheese** [comment] 2021-06-05 03:48
> 
> 
> The update is faulty, 2bored2wait-linux-x64-0.1.40, but 0.1.39 still works. The output of 0.1.40 is Segmentation fault.

i have triggered a re-run of the build process, the binaries should be updated in the next 10 minutes.

**Comment by nickcat325** [comment] 2021-06-08 12:35
0.1.42 spits out a long syntax error. 0.1.41 still works.

**Comment by KozmikNano** [comment] 2022-06-06 03:02
This has been fixed for awhile now

**Closed by KozmikNano** 2022-06-06 03:02 UTC
