### ISSUE TITLE
2b2t Restarts

### ISSUE THREAD

**Issue by Bluefox187** [themoonisacheese/2bored2wait#353] opened 2021-07-15 13:37 UTC
Pls fix the restarts because my proxy is still trying to reconnect after 2 hours and it says that 2b is down although it is not.
So maybe build a restart notification and change the auto reconnect time to a lower one so you get in faster. (or an option to change it)

**Comment by melod739** [comment] 2021-07-19 20:34
Yes please do. Everything works great. This would make it perfekt!

**Comment by TetrisLitHub** [comment] 2021-07-29 17:05
I have the same issue when running it and it's really irritating, if just this was fixed I would give this app a 5/5

**Comment by Thathip** [comment] 2021-08-04 05:12
I have the same issue

**Comment by NoobTracker** [comment] 2021-08-13 13:07
I have the same problem, 2b2w seems to be unable to reconnect after a restart, and maybe I have an explanation: When I use auto reconnect on my regular PC, I sometimes get stuck on the "Connecting ..." screen, seemingly forever. Maybe you should disconnect after 10s of this "screen".
Also, it would be useful if there were timestamps added to the console messages, that way I could see if it's actually the restart causing the problem or if other things might cause it, maybe bad internet.

**Comment by NoobTracker** [comment] 2021-08-18 08:30
Ummm ... I wonder if anyone wants to fix that ... I am certainly not smart enough.

**Comment by czho** [comment] 2021-11-01 05:21
because of this major issue I have to downgrade, is anyone working on this because its been like 3 months.

**Comment by rob9315** [comment] 2021-11-02 17:13
it is quite the weird bug indeed and i cannot pinpoint the issue and have kinda forgotten about its existence. sorry

**Comment by cristiioan** [comment] 2021-12-08 16:15
@rob9315 This can be solved quite easy. From what I  understand the authentification has to be remade or we can set an restart timeout(5 minutes) that is activated based on chat messgaes.

**Comment by HackerDaGreat57** [comment] 2021-12-18 20:35
Yeah I agree with @NoobTracker on the time-stamping part. Please make it 12-hour am-pm time, not the 24-hour mathematician's dream.

**Comment by rob9315** [comment] 2021-12-18 20:50
@HackerDaGreat57 I will have to respectfully disagree. I will not get into an argument on which time system is better or worse, i will only say that it should be system dependent, so that if you prefer am/pm time, you can set your system locale accordingly and same goes the other way.

**Comment by HackerDaGreat57** [comment] 2021-12-18 21:48
> @HackerDaGreat57 I will have to respectfully disagree. I will not get into an argument on which time system is better or worse, i will only say that it should be system dependent, so that if you prefer am/pm time, you can set your system locale accordingly and same goes the other way.

Right. Sorry. Forgot that configs existed for a second.

But will the timestamp be implemented?

**Comment by KozmikNano** [comment] 2022-06-06 22:51
cannot reproduce, please reopen if this issue persists. About the time stamp I will create a different issue!

**Comment by NepNep21** [comment] 2022-06-10 12:19
The issue persists in the latest commit from my experience, so i believe this should be reopened @KozmikNano 
![direct](https://user-images.githubusercontent.com/43792621/173062683-3fff66e0-5507-40e8-8dac-be511b3163d2.png)

**Comment by KozmikNano** [comment] 2022-06-10 12:21
@rob9315 i don’t think it’s then 2b2t.io being offline

**Comment by rob9315** [comment] 2022-06-10 12:22
of course not, that was a different issue which could crash the program when trying to use the `play` command

**Comment by KozmikNano** [comment] 2022-06-10 12:25
> of course not, that was a different issue which could crash the program when trying to use the `play` command

That makes sense! How would we go about fixing this is I can’t even reproduce it?

**Comment by NepNep21** [comment] 2022-06-10 12:26
It happens to me every time i use the automatic disconnect after queue end, not sure if thay helps

**Comment by KozmikNano** [comment] 2022-06-10 12:27
> It happens to me every time i use the automatic disconnect after queue end too, not sure if that helps

That helps a lot! Thanks

**Comment by rob9315** [comment] 2022-06-10 12:28
> It happens to me every time i use the automatic disconnect after queue end too, not sure if that helps
people use that?

i know this is an issue that can occur, but i can also not reproduce it well. i guess we can try to mitigate it by increasing the timeout when it fails to connect multiple times in a row

**Comment by KozmikNano** [comment] 2022-06-10 12:30
> > It happens to me every time i use the automatic disconnect after queue end too, not sure if that helps
> 
> people use that?
> 
> i know this is an issue that can occur, but i can also not reproduce it well. i guess we can try to mitigate it by increasing the timeout when it fails to connect multiple times in a row

That and I think there may be a issue with the account handling, would it be possible for it to think it has disconnected the account while the account never left the server?

**Comment by KozmikNano** [comment] 2022-06-10 12:34
Lol

**Comment by KozmikNano** [comment] 2022-09-16 18:56
Hopefully fixed with #485

**Closed by KozmikNano** 2022-09-16 18:56 UTC
Labels: bug
