### ISSUE TITLE
I get an errors after running npm start

### ISSUE THREAD

**Issue by SugarWasEaten** [themoonisacheese/2bored2wait#167] opened 2020-12-30 13:44 UTC
I don't really understand how this works, but I get an error after running npm start:

```
0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   'E:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'E:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'start'
1 verbose cli ]
2 info using npm@6.14.9
3 info using node@v14.15.3
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle 2bored2wait@1.0.0~prestart: 2bored2wait@1.0.0
6 info lifecycle 2bored2wait@1.0.0~start: 2bored2wait@1.0.0
7 verbose lifecycle 2bored2wait@1.0.0~start: unsafe-perm in lifecycle true
8 verbose lifecycle 2bored2wait@1.0.0~start: PATH: E:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;C:\Users\vanja\Desktop\2b2w\2bored2wait-master\node_modules\.bin;C:\Users\vanja\AppData\Roaming\npm;E:\Program Files\nodejs\;C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\Program Files (x86)\Common Files\Intel\Shared Libraries\redist\intel64\compiler;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\System32\OpenSSH\;E:\Windows\Program Files\Git\cmd;E:\Program Files\PuTTY\;E:\Program Files\nodejs\;C:\ProgramData\chocolatey\bin;C:\Users\vanja\AppData\Local\Microsoft\WindowsApps;E:\Users\vanja\AppData\Local\Programs\Microsoft VS Code\bin;C:\Users\vanja\AppData\Local\GitHubDesktop\bin;E:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2020.3\bin;;C:\PATH_Programs;C:\Users\vanja\AppData\Roaming\npm
9 verbose lifecycle 2bored2wait@1.0.0~start: CWD: C:\Users\vanja\Desktop\2b2w\2bored2wait-master
10 silly lifecycle 2bored2wait@1.0.0~start: Args: [ '/d /s /c', 'node main.js' ]
11 silly lifecycle 2bored2wait@1.0.0~start: Returned: code: 1  signal: null
12 info lifecycle 2bored2wait@1.0.0~start: Failed to exec start script
13 verbose stack Error: 2bored2wait@1.0.0 start: `node main.js`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (E:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:315:20)
13 verbose stack     at ChildProcess.<anonymous> (E:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:315:20)
13 verbose stack     at maybeClose (internal/child_process.js:1048:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)
14 verbose pkgid 2bored2wait@1.0.0
15 verbose cwd C:\Users\vanja\Desktop\2b2w\2bored2wait-master
16 verbose Windows_NT 10.0.19041
17 verbose argv "E:\\Program Files\\nodejs\\node.exe" "E:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
18 verbose node v14.15.3
19 verbose npm  v6.14.9
20 error code ELIFECYCLE
21 error errno 1
22 error 2bored2wait@1.0.0 start: `node main.js`
22 error Exit status 1
23 error Failed at the 2bored2wait@1.0.0 start script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

**Comment by CiscoEngry720** [comment] 2020-12-30 13:48
And also this:

```C:\Users\vanja\Desktop\2b2w\2bored2wait-master>npm start

> 2bored2wait@1.0.0 start C:\Users\vanja\Desktop\2b2w\2bored2wait-master
> node main.js


C:\Users\vanja\Desktop\2b2w\2bored2wait-master\main.js:23
        throw("error loading config file:\n" + err);
        ^
error loading config file:
SyntaxError: Unexpected token D in JSON at position 14
(Use `node --trace-uncaught ...` to show where the exception was thrown)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! 2bored2wait@1.0.0 start: `node main.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the 2bored2wait@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\vanja\AppData\Roaming\npm-cache\_logs\2020-12-30T13_47_15_048Z-debug.log

C:\Users\vanja\Desktop\2b2w\2bored2wait-master>```

**Comment by MrGeorgen** [comment] 2020-12-30 23:37
> And also this:
> 
> ```
> C:\Users\vanja\Desktop\2b2w\2bored2wait-master>npm start
> 
> > 2bored2wait@1.0.0 start C:\Users\vanja\Desktop\2b2w\2bored2wait-master
> > node main.js
> 
> 
> C:\Users\vanja\Desktop\2b2w\2bored2wait-master\main.js:23
>         throw("error loading config file:\n" + err);
>         ^
> error loading config file:
> SyntaxError: Unexpected token D in JSON at position 14
> (Use `node --trace-uncaught ...` to show where the exception was thrown)
> npm ERR! code ELIFECYCLE
> npm ERR! errno 1
> npm ERR! 2bored2wait@1.0.0 start: `node main.js`
> npm ERR! Exit status 1
> npm ERR!
> npm ERR! Failed at the 2bored2wait@1.0.0 start script.
> npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
> 
> npm ERR! A complete log of this run can be found in:
> npm ERR!     C:\Users\vanja\AppData\Roaming\npm-cache\_logs\2020-12-30T13_47_15_048Z-debug.log
> 
> C:\Users\vanja\Desktop\2b2w\2bored2wait-master>
> ```

your config.json is invalid

**Comment by AverageComet250** [comment] 2021-01-03 12:13
Can someone close this as the issue is resolved

**Closed** 2021-01-05 19:46 UTC

**Comment by SugarWasEaten** [comment] 2021-01-06 01:40
what the
