### ISSUE TITLE
Queue starting too early for the play command

### ISSUE THREAD

**Issue by weedoe** [themoonisacheese/2bored2wait#149] opened 2020-12-09 03:12 UTC
I have encountered a bug where the calculated time for when to queue is much too early. This causes for the player to join the server at unexpected times.

So far I have tried 06:00 and 13:00 for the play command and they both start too soon. Often the queue starts minutes after inputting the command despite the desired join time being more than 10 hours in the future. With the current queue times it only takes around 5 hours to join.

**Comment by MrGeorgen** [comment] 2020-12-09 17:34
duplicate of #141

**Closed by MrGeorgen** 2020-12-09 17:34 UTC
Labels: duplicate
