### ISSUE TITLE
`problem with npm start

### ISSUE THREAD

**Issue by HW12345** [themoonisacheese/2bored2wait#145] opened 2020-12-05 01:33 UTC
After I install git and the npm install works, but when it comes to npm start, it goes error.
C:\Users\-----\Desktop\2bored2wait-master\main.js:22
        throw("error loading config file:\n" + err);
        ^
error loading config file:
SyntaxError: Unexpected token D in JSON at position 14
(Use `node --trace-uncaught ...` to show where the exception was thrown)
npm ERR! code 1
npm ERR! path C:\Users\-----\Desktop\2bored2wait-master
npm ERR! command failed
npm ERR! command C:\Windows\system32\cmd.exe /d /s /c "node main.js"

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\-----\AppData\Local\npm-cache\_logs\2020-12-05T01_29_14_368Z-debug.log
Please help.

**Comment by HW12345** [comment] 2020-12-05 01:35
Also, sorry about the markdown problem.

**Comment by MrGeorgen** [comment] 2020-12-05 11:34
duplicate of #137

**Closed by MrGeorgen** 2020-12-05 11:34 UTC
Labels: duplicate
