### ISSUE TITLE
Not working anti afk and reconnect

### ISSUE THREAD

**Issue by FLamberoR** [themoonisacheese/2bored2wait#190] opened 2021-01-23 10:05 UTC
![image](https://user-images.githubusercontent.com/38767992/105575288-a07f7400-5d7b-11eb-8ca7-367dee1320bb.png)

**Comment by MrGeorgen** [comment] 2021-01-28 19:38
duplicate of #192 and #194

**Closed by MrGeorgen** 2021-01-28 19:38 UTC
