### ISSUE TITLE
whole entire program won't work

### ISSUE THREAD

**Issue by Razerviper** [themoonisacheese/2bored2wait#420] opened 2022-02-20 21:32 UTC
It was working for some time, but all of a sudden I keep getting this error. I can't even use the terminal anymore, nor the webserver because the whole thing just stops.

$ /Users/korgi/2bored2wait/node_modules/discord.js/src/rest/RequestHandler.js:154
      throw new DiscordAPIError(request.path, data, request.method, res.status);
            ^

DiscordAPIError: Unknown User
    at RequestHandler.execute (/Users/korgi/2bored2wait/node_modules/discord.js/src/rest/RequestHandler.js:154:13)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async RequestHandler.push (/Users/korgi/2bored2wait/node_modules/discord.js/src/rest/RequestHandler.js:39:14)
    at async UserManager.fetch (/Users/korgi/2bored2wait/node_modules/discord.js/src/managers/UserManager.js:67:18) {
  method: 'get',
  path: '/users/943300863454244885',
  code: 10013,
  httpStatus: 404
}

**Comment by Razerviper** [comment] 2022-02-21 22:30
> There seems to be a problem with your discord bot. This could be because your token changed or their api is down. You can start by resetting your config. If you are using the executable, the 2bored2wait config can be found at these places:
> 
> * gnu+linux /macos: `$HOME/.2bored2wait/config/local.json`
> * windows: `C:\Users\USERNAME\.2bored2wait\config\local.json`
> 
> If you are using the advanced install version then you can delete the config/local.json file

Hi, I used the advanced install version. I deleted the local.json file, but after it still didn't work. Tried reinstalling the program and my discord bot but also didn't work. I checked my token and it didn't change.

**Comment by KozmikNano** [comment] 2022-02-22 13:39
For now don’t enter a discord token. I will be investing this issue as well. I am sorry for the inconvenience

**Comment by Razerviper** [comment] 2022-02-22 23:45
> For now don’t enter a discord token. I will be investing this issue as well. I am sorry for the inconvenience

It's all fine. Another thing I wanted to point out that might help you is Cloudflare protection? (Supposedly this is for protecting against ddos attacks.) Here is my log.
https://pastebin.ubuntu.com/p/hwWfnRYvtW/

**Comment by Razerviper** [comment] 2022-02-23 03:50
Another update: Suddenly just worked. I can login. I don't know what happened, but I can login. Still getting cloudflare issue though

**Comment by Razerviper** [comment] 2022-02-27 03:51
I'm closing this because this thread is dead

**Comment by KozmikNano** [comment] 2022-02-27 13:23
Don’t worry I was still looking into it. After testing it multiple times I was unable to reproduce either of your problems. Do you have multiple accounts connected through t cloud flare servers?

**Comment by Edouard127** [comment] 2022-05-13 14:02
I was checking through main.js, and I noticed something
https://github.com/themoonisacheese/2bored2wait/blob/master/main.js#L91
`				if(!err) dc.users.fetch(id).then(user => {
					dcUser = user;
				});`

`dcUser = await client.users.fetch(id);`	
Should be a better idea

**Comment by KozmikNano** [comment] 2022-05-29 14:31
> if(!err) dcUser = await dc.users.fetch(id);

This wouldn't work. When completed ti throws this error ```await is only valid in async functions and the top level bodies of modules```

**Closed** 2022-05-29 14:32 UTC

**Comment by Edouard127** [comment] 2022-05-29 16:22
> > if(!err) dcUser = await dc.users.fetch(id);
> 
> 
> 
> This wouldn't work. When completed ti throws this error ```await is only valid in async functions and the top level bodies of modules```

Yes, that's why the code needs optimization and fixes
