### ISSUE TITLE
Anti-afk feature

### ISSUE THREAD

**Issue by awesomehd1** [themoonisacheese/2bored2wait#23] opened 2019-06-23 04:29 UTC
I found out that the server (queueskip) actually have a anti-afk and I wanted to think that’s a good feature.

If you don’t know what I Am talking about here is the flow chart:

Open Queue -> Finish Queue -> No players? <- Use anti afk <- If player logs on -> they play -> Finish? -> Quit the proxy.

Sorry if this flow chart is bad but anyways you can think about it.

Update edit: Removed “while using the application” since that sentence doesn’t make sense.

**Comment by sijanec** [comment] 2019-09-25 13:52
Note that unexpected afking on the server without users knowledge can lead to a "diseaster" --> someone may kill you while you are afking.

I have implemented a mechanism to send me SMS messages when I am 1h, 30min, 15min and 5 minutes from the start, so I get notified about the queue status every so often.

**Comment by themoonisacheese** [comment] 2019-09-26 08:16
i guess that's a thing that can exist.
for reference, the reason i haven't implemented an anti-afk is because 2b2t's afk detection is incredibly agressive, in addition to the proxy having no concept of what the world around you looks like, so it can't generate appropriate movement packets.

if you're insterested in developing side applications, i'd like to remind everyone that the proxy exposes information in JSON at the /update URI.

**Comment by sijanec** [comment] 2019-09-26 11:36
i think that sending a chat every 50 seconds will be enough. That's what I did and it works

**Comment by themoonisacheese** [comment] 2019-09-26 12:19
I looked at your repo, if that works then sure I can add that. maybe submit a pull request with only that change so you get full credit?

there still is the problem of having no world when you log back in ( you could still /kill but that still requires a bed nearby...) but at least you could stay connected even with a vanilla client.

**Comment by sijanec** [comment] 2019-09-27 04:48
I have looked into the protocol and there is no way to re-request the chunks. F3+A is indeed local.

I will test the antiafk and try to implement chunk saving stuff and then I will make a pull request. I never do anything in JS, so I am not really experienced...

**Comment by MrGeorgen** [comment] 2020-09-16 15:33
you can also check out my [fork](https://github.com/MrGeorgen/2smart2wait). I have also implemented other features like discord integration, chunk caching, custom ETA calculator and automatic reconnect .

**Comment by ZillyHuhn** [comment] 2020-09-16 19:05
@MrGeorgen why not pullrequest the improvements upstream? And also why didn't you fork on github and just wipe out the whole git history. Looks like you wrote the tool on your repo.

**Comment by sijanec** [comment] 2020-09-16 20:02
He probably wants to avoid touching the GitHUB interface as much as
possible and work via Git directly.

V V sre., 16. sep. 2020 ob 21:05 je oseba ZillyHuhn <
notifications@github.com> napisala:

**Comment by MrGeorgen** [comment] 2020-09-17 07:30
> @MrGeorgen why not pullrequest the improvements upstream? And also why didn't you fork on github and just wipe out the whole git history. Looks like you wrote the tool on your repo.

yeah to delete the git history was a dumb idea. I am not exactly why I did this, but it was the first time I worked with git.

**Comment by MrGeorgen** [comment] 2020-09-17 14:33
my fork is now merged #83

**Comment by ChillerDragon** [comment] 2020-09-17 17:40
Thanks for your contribution @MrGeorgen so fast as well!

**Comment by ZillyHuhn** [comment] 2020-09-17 17:46
Thanks for your contribution @MrGeorgen so fast as well!

**Comment by themoonisacheese** [comment] 2020-09-18 07:26
since the issue is resolved, i'm closing this. thanks @MrGeorgen for really putting the work.

**Closed by themoonisacheese** 2020-09-18 07:26 UTC
Labels: enhancement
