### ISSUE TITLE
Queueing randomly stops

### ISSUE THREAD

**Issue by viluzi** [themoonisacheese/2bored2wait#15] opened 2019-06-05 13:43 UTC
While waiting in queue using this proxy, it randomly disconnects. not sure if that is a problem with 2b2t itself. Automatically reconnecting would be nice

**Comment by themoonisacheese** [comment] 2019-06-05 13:45
closed as duplicate of #3

**Closed by themoonisacheese** 2019-06-05 13:45 UTC

**Comment by viluzi** [comment] 2019-06-05 14:01
wouldnt call it a duplicate. i literally get disconnected, q doesnt break. it just stops. stop button chages into start

**Comment by themoonisacheese** [comment] 2019-06-05 14:03
ah. I can't fix that. the proxy should reconnect automatically though.

**Comment by viluzi** [comment] 2019-06-05 14:05
all i can say its frustrating that after a while in q with it it stops. if it cant be fixed ill live with it.

**Comment by themoonisacheese** [comment] 2019-06-05 14:07
this happens when 2b2t lags out. Except from snapping away half of etikas fan base, I can't do much about it.
