### ISSUE TITLE
crashes when 2b2t.io is down when trying to use `play xx:xx`

### ISSUE THREAD

**Issue by catofworld123** [themoonisacheese/2bored2wait#424] opened 2022-03-22 12:46 UTC
![Командная строка 22 03 2022 12_02_59](https://user-images.githubusercontent.com/80473111/159425811-feccb6e9-8296-46cd-858a-1939a754a3f5.png)

**Comment by nickcat325** [comment] 2022-05-31 09:05
Are you still having this problem? Update 2b2w and run `npm update && npm start` .

**Comment by KozmikNano** [comment] 2022-06-06 02:53
I am unable to reproduce this! Are you still having this issue?

**Comment by rob9315** [comment] 2022-06-06 21:56
2b2t.io was down at the time is what i'm guessing
we should make it independent of that service

**Comment by KozmikNano** [comment] 2022-06-06 23:28
Fixed in pr

**Closed by KozmikNano** 2022-06-06 23:28 UTC
