### ISSUE TITLE
auto build docker images

### ISSUE THREAD

**Issue by MrGeorgen** [themoonisacheese/2bored2wait#289] opened 2021-05-04 12:27 UTC
currently I build the docker per pre-push git hook, so the docker image is
only updated if I push something. @themoonisacheese  can you create a docker
account link it with your github account and configure auto builds. You can
also publish it under a team, that might be good for future use cases

**Comment by themoonisacheese** [comment] 2021-05-04 13:06
https://hub.docker.com/r/2bored2wait/2bored2wait
i published it under an org, give me your docker id if you want to be added.
the auto builds have been setup pretty much by default, i have no idea if there is more i should be doing.

**Comment by MrGeorgen** [comment] 2021-05-04 15:42
thanks, at the moment it only builds for amd64, building for arm would be
nice. I looked it up and unfortunely docker hub only support auto builds for amd64. However
we can build for other archs by using a github action. As I don't want to
share my docker password with github, you can create a dummy docker account
which only is in our organisation and add the username and password as github
secret

**Comment by themoonisacheese** [comment] 2021-05-04 17:56
it doesn't look like github actions supports running on arm as per https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idruns-on .
i have seen a few people saying it is possible to run qemu in order to build in arm, but this is way above my head as i've worked with docker precisely once.


pinging @dsetareh for docker voodoo .
reopening until an arm solution is found.

**Comment by MrGeorgen** [comment] 2021-05-04 18:23
>i have seen a few people saying it is possible to run qemu in order to build in arm, but this is way above my head as i've worked with docker precisely once.

Apart from this project, I also don't work with docker. I guess using qemu can
get really messy. However I found an [example](https://github.com/docker/build-push-action/blob/master/docs/advanced/multi-platform.md) from the offical docker organization which is surpisingly simple

**Comment by MrGeorgen** [comment] 2021-05-04 18:41
you can also add me to the organization. My docker id is mrgeorgen

**Comment by themoonisacheese** [comment] 2021-05-04 19:08
good find. i've set up an action with that snippet (which uses  quemu btw, just in a controlled way), which required minimal changes. i've also decided to move the amd64 build on github actions so that the builds are centralized (and it supposedly uses the same build engine as on docker hub anyways).
https://github.com/themoonisacheese/2bored2wait/actions/workflows/docker-arm.yml
i've also added you as a member of the org on docker.

closing since the issue is resolved.

**Closed by themoonisacheese** 2021-05-04 19:08 UTC

**Comment by MrGeorgen** [comment] 2021-05-04 21:10
nice, I also added a few addtional platforms and auto updating the docker hub
description
