### ISSUE TITLE
Crashing after reconnecting too many times

### ISSUE THREAD

**Issue by HyCore** [themoonisacheese/2bored2wait#269] opened 2021-04-25 11:36 UTC
Here is the issue: 
```Queue is finished
Connection reset by 2b2t server. Reconnecting...
Reconnecting...
Connection reset by 2b2t server. Reconnecting...
Reconnecting...
$ /var/www/html/2bored2wait/node_modules/minecraft-protocol/src/transforms/framing.js:67
          } else { throw e }
                   ^

TypeError: Cannot read property 'id' of undefined
    at Conn.generatePackets (/var/www/html/2bored2wait/node_modules/mcproxy/dist/conn.js:101:43)
    at Conn.sendPackets (/var/www/html/2bored2wait/node_modules/mcproxy/dist/conn.js:90:28)
    at Server.<anonymous> (/var/www/html/2bored2wait/main.js:290:8)
    at Server.emit (events.js:315:20)
    at loginClient (/var/www/html/2bored2wait/node_modules/minecraft-protocol/src/server/login.js:127:12)
    at Client.onLogin (/var/www/html/2bored2wait/node_modules/minecraft-protocol/src/server/login.js:49:7)
    at Object.onceWrapper (events.js:422:26)
    at Client.emit (events.js:315:20)
    at FullPacketParser.<anonymous> (/var/www/html/2bored2wait/node_modules/minecraft-protocol/src/client.js:91:12)
    at FullPacketParser.emit (events.js:315:20)
```

**Comment by MrGeorgen** [comment] 2021-04-29 19:49
looks like a mcproxy issue

**Comment by rob9315** [comment] 2021-05-01 21:24
@MrGeorgen can you look into making mcproxy more crash-safe? like adding a try-catch statement somewhere, so it just doesn't crash even if something went wrong?

**Comment by rob9315** [comment] 2021-05-02 03:03
@HyCore I have not been able to reproduce this issue, as it says reconnecting a lot, this is probably unfortunate timing matching a server restart. I will still add a try statement somewhere to stop it from crashing

**Comment by HyCore** [comment] 2021-05-05 08:57
Okey thanks. I think to reproduce the issue you need to have a client that autoreconnect to the proxy while this one is trying to connect on. Btw could you send me your discord ?

**Comment by rob9315** [comment] 2021-05-05 12:41
Rob9315#9315 on discord

**Comment by rob9315** [comment] 2021-05-15 19:14
I think this might be fixed now. Please reopen if the issue still persists

**Closed by rob9315** 2021-05-15 19:14 UTC
