### ISSUE TITLE
Alert users when there’s a new update 

### ISSUE THREAD

**Issue by wylie39** [themoonisacheese/2bored2wait#115] opened 2020-10-06 19:38 UTC
Alert users when there’s a new update to the software. May work on this if it would be helpful.

**Comment by KozmikNano** [comment] 2021-05-04 13:13
@MrGeorgen I think I may be able to implement a fix to this, would you like me to attempt to implement this into the code and then send you a copy of the edit. It will take 1-7 days.

**Comment by themoonisacheese** [comment] 2021-05-04 13:15
a better way would be to fork this repo and make a pull request.

**Comment by KozmikNano** [comment] 2021-05-04 13:16
I may sound dumb but how do I do that?

**Comment by MrGeorgen** [comment] 2021-05-04 13:56
- Click where I have my cursor to create a fork
![image](https://user-images.githubusercontent.com/65063405/117014241-e770f400-acf0-11eb-8048-4e94c6dc20e4.png)
- make edits in your forked repo
- then click the pull request tab in your repo
- click on "New pull request"

**Comment by themoonisacheese** [comment] 2021-05-04 13:58
this video tutorial is also good.
https://www.youtube.com/watch?v=rgbCcBNZcdQ

**Comment by KozmikNano** [comment] 2021-05-04 14:01
thanks for that, I am going to start working on the system!

**Comment by KozmikNano** [comment] 2021-05-05 16:22
Ok, i have completely finished editing the system and making it work as intended. it is waiting approval by you guys! instruction on configuring is in the description of the pull request. only one thing needs to be changed and if you have a question you can ask here.

**Comment by KozmikNano** [comment] 2021-05-06 11:57
@MrGeorgen and @themoonisacheese, I don’t know if you guys have seen it yet I have made a pull request with the updated code. This new code would resolve this issue.

**Comment by KozmikNano** [comment] 2021-05-06 13:26
@themoonisacheese and @MrGeorgen I have addressed the issue and it is now ready unless you guys need me to change something!

**Comment by KozmikNano** [comment] 2021-05-06 18:36
@themoonisacheese or @MrGeorgen you can resolve this now.

**Comment by themoonisacheese** [comment] 2021-05-06 19:24
Fixed via #292

**Closed** 2021-05-06 19:24 UTC
Labels: enhancement
