### ISSUE TITLE
ETA and Player Queue are messed up

### ISSUE THREAD

**Issue by alex89912** [themoonisacheese/2bored2wait#566] opened 2023-08-09 07:26 UTC
### The Bug
To start of with, the bug is simple but very annoying, it says that there is more players in the queue than it should be, and so the ETA is fully messed up with negative times.

### How to reproduce?
Just use V3.3.0 with microsoft

#### Another question, but not necessary:
Why do i log in to MC for Nintendo Switch to use it?

**Comment by themoonisacheese** [comment] 2023-08-09 14:40
closing as duplicate of  #553

**Closed by themoonisacheese** 2023-08-09 14:40 UTC

**Comment by rob9315** [comment] 2023-08-10 17:41
> Why do i log in to MC for Nintendo Switch to use it?

Take a look at the [used library](https://github.com/prismarinejs/mineflayer) for technical details
